#!/usr/bin/env bash

if [[ "${1}" != "skip" ]]; then
  ansible-galaxy role install -r requirements.yml
  ansible-galaxy collection install -r requirements.yml
fi

shift

ansible-playbook --diff --ask-become-pass -e "@secrets.yaml" -i inventory.yml setup.yaml "$@"
