#!/usr/bin/env bash

#ansible-galaxy role install -r requirements.yml
#ansible-galaxy collection install -r requirements.yml

ansible-playbook --ask-become-pass -e "@secrets.yaml" -i inventory.yml setup.yaml
