---
roles:
  - src: https://github.com/leonallen22/ansible-role-keybase.git
    name: ansible-role-keybase
    scm: git
    version: master
  - src: oefenweb.dropbox
  - src: patrick-hill.franz
  - src: cloudalchemy.node_exporter
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.grafana

collections:
  - name: community.general
  - name: community.crypto
  - name: ansible.posix