---
roles:
  - src: https://github.com/bhechinger/ansible-role-keybase.git
    name: ansible-role-keybase
    scm: git
    version: patch-1
  - src: oefenweb.dropbox
  - src: patrick-hill.franz
  - src: cloudalchemy.node_exporter
  - src: cloudalchemy.prometheus
  - src: cloudalchemy.grafana
  - src: stefangweichinger.ansible_rclone
  - src: geerlingguy.postgresql
  - src: https://github.com/bhechinger/ansible-nsq.git
    name: ansible-nsq
    scm: git
    version: master
  - src: https://github.com/ansible-community/ansible-consul.git
    name: ansible-consul
    scm: git
    version: master

collections:
  - name: community.general
  - name: community.crypto
  - name: community.rabbitmq
  - name: ansible.posix
